name: Build Winget Index

on:
  workflow_dispatch:  # Ejecutar manualmente

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Descargar WingetCreate directamente del release oficial
      - name: Download WingetCreate
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://github.com/microsoft/winget-create/releases/download/v1.10.3.0/wingetcreate.exe -OutFile wingetcreate.exe
          dir

      # 3️⃣ Crear carpeta de salida
      - name: Ensure output folder exists
        run: mkdir output

      # 4️⃣ Copiar los manifiestos a output
      - name: Copy manifests to output
        run: Copy-Item -Path .\manifests\* -Destination .\output\manifests -Recurse

      # 5️⃣ Generar index.db usando la copia local de wingetcreate
      - name: Generate Winget index
        shell: pwsh
        run: |
          .\wingetcreate.exe source export -o output

      # 6️⃣ Publicar en gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages



